name: Build and deploy a container to an Azure Web App

env:
  REGISTRY: ${{ secrets.REGISTRY_LOGIN_SERVER }}
  AZURE_WEBAPP_NAME: WA-DevPD-Dev-ScaffoldAppContainerization
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches: [ "sample-nodejs" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: 'Azure Login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          push: true
          build-args: |
            version=${{ steps.meta.outputs.tags }}
          tags: ${{ steps.meta.outputs.tags }}
          file: ./Dockerfile